### ISSUE TITLE
How to load precomputed depth?

### ISSUE THREAD

**Issue by mtangemann** [timmh/socrates#1]
Hi Timm,

Thank you very much for your efforts to open source your dataset and codebase!

I am trying to load the precomputed depth in meters for the [labelled images](https://zenodo.org/record/7035934), but I'm not sure whether I do it correctly. The data doesn't seem do be depth directly, since the values don't fit at all (greater values for pixels closer to the camera):

```python
data = cv2.imread("images/20220209150523_000090.exr", cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)

plt.matshow(data)
plt.colorbar()
```

![grafik](https://user-images.githubusercontent.com/1290242/198229505-aa4d5ced-0c94-452b-90f7-0cb203703167.png)

So I am assuming that the data is disparity in pixels. Converting to depth using the parameters from [utils/prepare_distance_sampling.py](https://github.com/timmh/socrates/blob/main/utils/prepare_distance_sampling.py) looks more sensible, but a maximal distance of >200m seems to be quite far.

```python
camera_baseline = 0.25  # meters
camera_horizontal_pixels = 1920  # pixels
camera_horizontal_sensor_size = 0.007564  # meters
camera_disparity_to_depth_factor = camera_focal_length * camera_baseline * camera_horizontal_pixels * camera_horizontal_sensor_size ** -1

plt.matshow(camera_disparity_to_depth_factor / data)
plt.colorbar()
```

![grafik](https://user-images.githubusercontent.com/1290242/198230500-7f7f3b69-58e3-4041-bbf2-1945d567e45c.png)

It would be super helpful if you could add a code snippet showing how to correctly load the precomputed depth data.

Thank you,
Matthias

**Comment by timmh** [comment]
Hi Matthias,

you are correct, the EXR files contain disparity in pixels. I just re-checked the rectification, EXR extraction and the [parameters](https://github.com/timmh/socrates/blob/ef54f613fdb82e5047c94835779c0ecbfd1cb6d5/utils/prepare_distance_sampling.py) you used, and everything seems to be correct. I also just performed ground truth measurements using a laser rangefinder, which match the distances obtained using the parameters above. Note that the baseline for this experiment was just 25cm, so measurements at large distances are expected to have huge errors. The actual largest distance, at the fence in the top left of the image, is around 140m, according to my laser rangefinder.

Please let me know if this answers your question or if I can be of help. Best,
Timm

**Comment by mtangemann** [comment]
Hi Timm,

Thank you for your reply and even doing ground truth measurements! My main concern was that I might use the data in the wrong way; this has been addressed so I'll close this issue.

Thank you,
Matthias
